version: '3.8'

services:
  db:
    container_name: mysql_57
    image: mysql:5.7.36
    networks:
      cloud_net:
        ipv4_address: 172.16.238.2
    ports:
      - "3306:3306"
    volumes:
      - D:\VirtualMachine\MySQL\conf:/etc/mysql/conf.d
      - D:\VirtualMachine\MySQL\logs:/logs
      - D:\VirtualMachine\MySQL\data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  docker-nacos-server:
    container_name: nacos-server-master
    image: nacos/nacos-server:1.4.2
    ports:
      - "8848:8848"
    networks:
      cloud_net:
        ipv4_address: 172.16.238.10
    restart: on-failure
    privileged: true
    volumes:
      - D:\VirtualMachine\Nacos\node-1:/home/nacos/logs
      # 2.x开启
#      - D:\VirtualMachine\Nacos\init.d\custom.properties:/home/nacos/init.d/custom.properties
    environment:
      #nacos dev env
      NACOS_SERVERS: 172.16.238.10:8848 172.16.238.11:8848
      # MYSQL
      MYSQL_SERVICE_HOST: 172.16.238.2
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      # JVM
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 256m
  nacos-server-slave:
    container_name: nacos-server-slave
    image: nacos/nacos-server:1.4.2
    networks:
      cloud_net:
        ipv4_address: 172.16.238.11
    ports:
      - "8849:8848"
    restart: on-failure
    privileged: true
    volumes:
      - D:\VirtualMachine\Nacos\node-1:/home/nacos/logs
      # 2.x开启
#      - D:\VirtualMachine\Nacos\init.d\custom.properties:/home/nacos/init.d/custom.properties
    environment:
      #nacos dev env
      NACOS_SERVERS: 172.16.238.10:8848 172.16.238.11:8848
      # MYSQL
      MYSQL_SERVICE_HOST: mysql_57
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      # JVM
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 256m

networks:
  cloud_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24