spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 授权服务
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 系统服务
        - id: system
          uri: lb://system
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
            # 降级配置
#            - name: Hystrix
#              args:
#                name: default
#                # 降级接口的地址
#                fallbackUri: 'forward:/fallback'
        # 文件服务
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1