spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 系统服务
        - id: system
          uri: lb://system
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
        # 文件服务
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1